### ISSUE TITLE
Long term access_id problems

### ISSUE THREAD

**Issue by mrclay** [arckinteractive/elgg_solr#18]
For non-admin users in a lot of ACLs, the HTTP Solr queries become quite large. Due to a complex access requirement we have some users that are in +2000 ACLs and the resulting Solr query is 12500 bytes. That's well under Tomcat's default POST limit of 2MB, yet I'm getting failed responses (I'll have more info on the Solr side tomorrow when I can access that host).

Have you run into anything like this yet?

**Comment by beck24** [comment]
I haven't, but I don't believe I have any instances with that many acls for a single user.
I'm not sure what to suggest offhand, my solr knowledge isn't all that advanced, it's come almost entirely from this plugin and making things work as I've needed it to and debugging anything that breaks.  If you get any more info please let me know.

One thing I've found since I wrote this is the IN() type clause of solr doesn't need an OR stated, currently the access query looks like 'access_id:(123 OR 234 OR 345 OR 456)' where a space is all that's needed

'access_id:(123 234 345 456)'

Not necessarily a silver bullet fix, but over 2000 acls those 'OR's are going to add up.

**Comment by mrclay** [comment]
Yes, saving 3 bytes per ACL would help. Thx!

**Comment by beck24** [comment]
I've removed all the "OR"s from those access filters.  Not sure what else could be done if there are still enough acls to max it out...  If you think of anything let me know
